[build]
  command = "CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/car--repair-sheffield/index.html"
  status = 200

[build.environment]
  PUBLIC_URL = "/car--repair-sheffield" 